Video: Send VIDEO_STREAM_INFORMATION to GCS
stephendade/Rpanion-server pull request #201
Opened 2024-02-07 06:20 UTC by ddd999

Addresses feature request issue #169

Enables Rpanion to respond to send COMMAND_ACK and VIDEO_STREAM_INFORMATION messages via MavLink in response to a MAV_CMD_REQUEST_MESSAGE.

2024-02-08 02:23 UTC, ddd999 commented
Converting to draft because I realized it's going to be mandatory to have a way to select the network interface (and therefore, which URI gets send in the VIDEO_STREAM_INFORMATION) message. This would work fine hardcoded, but there are plenty of use cases where a user would want to choose.

2024-02-10 06:08 UTC, stephendade commented
Nice! When you're ready, happy to give it test and review.

2024-03-03 00:59 UTC, ddd999 commented
@stephendade, please review when you have time. Thank you!

Thanks to @TyIsI for helping with tips to get this working as well.

2024-03-03 10:22 UTC, stephendade commented
Great! Looks like you'll need a rebase first, as some of my recent tlogging changes aren't in here.

2024-03-07 05:55 UTC, ddd999 commented
@stephendade I had a bit of fight with git but I believe it is all up to date now.

2024-03-07 09:40 UTC, stephendade commented
Yes, that look up to date now. I should have some time in the next few days to review.

2024-03-11 05:19 UTC, stephendade requested changes
Looks pretty good. Some minor formatting issues and the user needs a bit more information about the service.

2024-03-11 05:25 UTC, stephendade requested changes

2024-03-11 05:25 UTC, stephendade commented on src/video.js
> +        <div className="form-group row" style={{ marginBottom: '5px' }}>
<br />
        <h3>MAVLink Video Streaming Service</h3>
        <p><i>Configuration for advertising the video stream via MAVLink. See <a href='https://mavlink.io/en/services/camera.html#video_streaming'>here</a> for details.</i></p>
        <div className="form-group row" style={{ marginBottom: '5px' }}>
          <label className="col-sm-4 col-form-label">Video source IP Address</label>
          <div className="col-sm-8">
            <Select isDisabled={this.state.streamingStatus} onChange={this.handleMavStreamChange} options={this.state.ifaces.map((item, index) => ({ value: index, label: item}))} value={this.state.mavStreamSelected} />
          </div>
        </div>

2024-03-11 05:25 UTC, stephendade commented on src/video.js
> +        <div className="form-group row" style={{ marginBottom: '5px' }}>
Also needs the "Stream Configuration" header changed to h3 to match here

2024-03-11 05:25 UTC, stephendade commented on mavlink/mavManager.js
> +      ){
Space between brackets

2024-03-11 05:25 UTC, stephendade commented on mavlink/mavManager.js
> +        // Respond to MavLink commands that are targeted to the companion computer
Remove any extraneous trailing whitespaces from this section

2024-03-13 01:15 UTC, stephendade commented
Looks good! Merging...

2024-03-13 01:15 UTC, merged